"""agregar enums y campo description

Revision ID: 8220e56b9586
Revises: bf9c514f3e7c
Create Date: 2025-07-19 12:38:30.224934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8220e56b9586'
down_revision: Union[str, None] = 'bf9c514f3e7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agenda', sa.Column('description', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agenda', 'description')
    # ### end Alembic commands ###
