"""agregar enums a modelos

Revision ID: f85fe186b6cb
Revises: 8220e56b9586
Create Date: 2025-07-19 12:51:01.093000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f85fe186b6cb'
down_revision: Union[str, None] = '8220e56b9586'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()

    # Crear los tipos ENUM solo si no existen
    sa.Enum('RUNNING', 'DELETED', 'PAYMENT_DUE', name='account_status').create(bind, checkfirst=True)
    sa.Enum('ACTIVE', 'INACTIVE', name='file_status').create(bind, checkfirst=True)
    sa.Enum('PAYED', 'DUE', 'OVERDUE', name='invoice_status').create(bind, checkfirst=True)
    sa.Enum(
        'CIVIL', 'PENAL', 'LABORAL', 'CONTENCIOSO_ADMINISTRATIVO', 'MERCANTIL',
        'RECLAMOS_MENORES', 'FAMILIA', 'ADMINISTRATIVO', 'FISCAL',
        'CONSTITUCIONAL', 'AMBIENTAL', 'INTERNACIONAL',
        name='case_type_legal_case'
    ).create(bind, checkfirst=True)
    sa.Enum('NORMAL', 'MID', 'HIGH', name='priority_level_legal_case').create(bind, checkfirst=True)
    sa.Enum('VICTORIA', 'DERROTA', 'ACTIVO', 'CONCILIACION', name='status_legal_case').create(bind, checkfirst=True)
    sa.Enum('ACTIVE', 'INACTIVE', name='user_status').create(bind, checkfirst=True)

    # Alterar las columnas usando los tipos ENUM recién creados
    op.execute("ALTER TABLE account ALTER COLUMN status TYPE account_status USING status::account_status")
    op.execute("ALTER TABLE file ALTER COLUMN status TYPE file_status USING status::file_status")
    op.execute("ALTER TABLE invoice ALTER COLUMN status TYPE invoice_status USING status::invoice_status")
    op.execute("ALTER TABLE legal_case ALTER COLUMN case_type TYPE case_type_legal_case USING case_type::case_type_legal_case")
    op.execute("ALTER TABLE legal_case ALTER COLUMN priority_level TYPE priority_level_legal_case USING priority_level::priority_level_legal_case")
    op.execute("ALTER TABLE legal_case ALTER COLUMN status TYPE status_legal_case USING status::status_legal_case")
    op.execute("ALTER TABLE \"user\" ALTER COLUMN status TYPE user_status USING status::user_status")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'status',
               existing_type=sa.Enum('ACTIVE', 'INACTIVE', name='user_status'),
               type_=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('legal_case', 'status',
               existing_type=sa.Enum('VICTORIA', 'DERROTA', 'ACTIVO', 'CONCILIACION', name='status_legal_case'),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.alter_column('legal_case', 'priority_level',
               existing_type=sa.Enum('NORMAL', 'MID', 'HIGH', name='priority_level_legal_case'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('legal_case', 'case_type',
               existing_type=sa.Enum('CIVIL', 'PENAL', 'LABORAL', 'CONTENCIOSO_ADMINISTRATIVO', 'MERCANTIL', 'RECLAMOS_MENORES', 'FAMILIA', 'ADMINISTRATIVO', 'FISCAL', 'CONSTITUCIONAL', 'AMBIENTAL', 'INTERNACIONAL', name='case_type_legal_case'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('invoice', 'status',
               existing_type=sa.Enum('PAYED', 'DUE', 'OVERDUE', name='invoice_status'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('file', 'status',
               existing_type=sa.Enum('ACTIVE', 'INACTIVE', name='file_status'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('account', 'status',
               existing_type=sa.Enum('RUNNING', 'DELETED', 'PAYMENT_DUE', name='account_status'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
